services:
  app:
    image: ghcr.io/justlovemaki/prismflowagent
    build: .
    container_name: PrismFlowAgent
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./data:/app/data
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - JWT_SECRET=${JWT_SECRET:-your_secret_here}
